server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ExpertSystem?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      #url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password:

  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 3000       # 连接超时时间 单位 ms（毫秒）
    #    cluster:
    #      nodes: 10.3.1.4:7000,10.3.1.4:7001,...,10.3.1.4:7008
    pool:
      max-idle: 8       # 连接池中的最大空闲连接，默认值也是8
      min-idle: 0       # 连接池中的最小空闲连接，默认值也是0
      max-active: 8     # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-wait: -1      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

#邮箱发送配置
email:
  address: m15626174022@163.com
  password: IIBTIIFILHDAFDTZ
  account: m15626174022@163.com
  port: 465
